
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="x" uri="http://java.sun.com/jsp/jstl/xml" %>

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
</head>
  <body>
        <x:parse var="zale">
          <?xml version="1.0" encoding="utf-8"?>
          <plane_zale>
            <row>
              <row_number>1</row_number>
              <place>
                <number>1</number>
                <price>1000</price>
              </place>
              <place>
                <number>2</number>
                <price>1000</price>
              </place>
              <place>
                <number>3</number>
                <price>1000</price>
              </place>
              <place>
                <number>4</number>
                <price>1000</price>
              </place>
              <place>
                <number>5</number>
                <price>1000</price>
              </place>
              <place>
                <number>6</number>
                <price>1000</price>
              </place>
              <place>
                <number>7</number>
                <price>1000</price>
              </place>
              <place>
                <number>8</number>
                <price>1000</price>
              </place>
              <place>
                <number>9</number>
                <price>1000</price>
              </place>
              <place>
                <number>10</number>
                <price>1000</price>
              </place>
              <place>
                <number>11</number>
                <price>1000</price>
              </place>
              <place>
                <number>12</number>
                <price>1000</price>
              </place>
              <place>
                <number>13</number>
                <price>1000</price>
              </place>
              <place>
                <number>14</number>
                <price>1000</price>
              </place>
              <place>
                <number>15</number>
                <price>1000</price>
              </place>
              <place>
                <number>16</number>
                <price>1000</price>
              </place>
            </row>
            <row >
              <row_number>2</row_number>
              <place>
                <number>1</number>
                <price>1000</price>
              </place>
              <place>
                <number>2</number>
                <price>1000</price>
              </place>
              <place>
                <number>3</number>
                <price>1000</price>
              </place>
              <place>
                <number>4</number>
                <price>1000</price>
              </place>
              <place>
                <number>5</number>
                <price>1000</price>
              </place>
              <place>
                <number>6</number>
                <price>1000</price>
              </place>
              <place>
                <number>7</number>
                <price>1000</price>
              </place>
              <place>
                <number>8</number>
                <price>1000</price>
              </place>
              <place>
                <number>9</number>
                <price>1000</price>
              </place>
              <place>
                <number>10</number>
                <price>1000</price>
              </place>
              <place>
                <number>11</number>
                <price>1000</price>
              </place>
              <place>
                <number>12</number>
                <price>1000</price>
              </place>
              <place>
                <number>13</number>
                <price>1000</price>
              </place>
              <place>
                <number>14</number>
                <price>1000</price>
              </place>
              <place>
                <number>15</number>
                <price>1000</price>
              </place>
              <place>
                <number>16</number>
                <price>1000</price>
              </place>
            </row>
            <row>
              <row_number>3</row_number>
              <place>
                <number>1</number>
                <price>1000</price>
              </place>
              <place>
                <number>2</number>
                <price>1000</price>
              </place>
              <place>
                <number>3</number>
                <price>1000</price>
              </place>
              <place>
                <number>4</number>
                <price>1000</price>
              </place>
              <place>
                <number>5</number>
                <price>1000</price>
              </place>
              <place>
                <number>6</number>
                <price>1000</price>
              </place>
              <place>
                <number>7</number>
                <price>1000</price>
              </place>
              <place>
                <number>8</number>
                <price>1000</price>
              </place>
              <place>
                <number>9</number>
                <price>1000</price>
              </place>
              <place>
                <number>10</number>
                <price>1000</price>
              </place>
              <place>
                <number>11</number>
                <price>1000</price>
              </place>
              <place>
                <number>12</number>
                <price>1000</price>
              </place>
              <place>
                <number>13</number>
                <price>1000</price>
              </place>
              <place>
                <number>14</number>
                <price>1000</price>
              </place>
              <place>
                <number>15</number>
                <price>1000</price>
              </place>
              <place>
                <number>16</number>
                <price>1000</price>
              </place>
            </row>
            <row>
              <row_number>4</row_number>
              <place>
                <number>1</number>
                <price>1000</price>
              </place>
              <place>
                <number>2</number>
                <price>1000</price>
              </place>
              <place>
                <number>3</number>
                <price>1000</price>
              </place>
              <place>
                <number>4</number>
                <price>1000</price>
              </place>
              <place>
                <number>5</number>
                <price>1000</price>
              </place>
              <place>
                <number>6</number>
                <price>1000</price>
              </place>
              <place>
                <number>7</number>
                <price>1000</price>
              </place>
              <place>
                <number>8</number>
                <price>1000</price>
              </place>
              <place>
                <number>9</number>
                <price>1000</price>
              </place>
              <place>
                <number>10</number>
                <price>1000</price>
              </place>
              <place>
                <number>11</number>
                <price>1000</price>
              </place>
              <place>
                <number>12</number>
                <price>1000</price>
              </place>
              <place>
                <number>13</number>
                <price>1000</price>
              </place>
              <place>
                <number>14</number>
                <price>1000</price>
              </place>
              <place>
                <number>15</number>
                <price>1000</price>
              </place>
              <place>
                <number>16</number>
                <price>1000</price>
              </place>
            </row>
            <row>
              <row_number>5</row_number>
              <place>
                <number>1</number>
                <price>1000</price>
              </place>
              <place>
                <number>2</number>
                <price>1000</price>
              </place>
              <place>
                <number>3</number>
                <price>1000</price>
              </place>
              <place>
                <number>4</number>
                <price>1000</price>
              </place>
              <place>
                <number>5</number>
                <price>1000</price>
              </place>
              <place>
                <number>6</number>
                <price>1000</price>
              </place>
              <place>
                <number>7</number>
                <price>1000</price>
              </place>
              <place>
                <number>8</number>
                <price>1000</price>
              </place>
              <place>
                <number>9</number>
                <price>1000</price>
              </place>
              <place>
                <number>10</number>
                <price>1000</price>
              </place>
              <place>
                <number>11</number>
                <price>1000</price>
              </place>
              <place>
                <number>12</number>
                <price>1000</price>
              </place>
              <place>
                <number>13</number>
                <price>1000</price>
              </place>
              <place>
                <number>14</number>
                <price>1000</price>
              </place>
              <place>
                <number>15</number>
                <price>1000</price>
              </place>
              <place>
                <number>16</number>
                <price>1000</price>
              </place>
            </row>
            <row>
              <row_number>6</row_number>
              <place>
                <number>1</number>
                <price>1000</price>
              </place>
              <place>
                <number>2</number>
                <price>1000</price>
              </place>
              <place>
                <number>3</number>
                <price>1000</price>
              </place>
              <place>
                <number>4</number>
                <price>1000</price>
              </place>
              <place>
                <number>5</number>
                <price>1000</price>
              </place>
              <place>
                <number>6</number>
                <price>1000</price>
              </place>
              <place>
                <number>7</number>
                <price>1000</price>
              </place>
              <place>
                <number>8</number>
                <price>1000</price>
              </place>
              <place>
                <number>9</number>
                <price>1000</price>
              </place>
              <place>
                <number>10</number>
                <price>1000</price>
              </place>
              <place>
                <number>11</number>
                <price>1000</price>
              </place>
              <place>
                <number>12</number>
                <price>1000</price>
              </place>
              <place>
                <number>13</number>
                <price>1000</price>
              </place>
              <place>
                <number>14</number>
                <price>1000</price>
              </place>
              <place>
                <number>15</number>
                <price>1000</price>
              </place>
              <place>
                <number>16</number>
                <price>1000</price>
              </place>
            </row>
            <row>
              <row_number>7</row_number>
              <place>
                <number>1</number>
                <price>1000</price>
              </place>
              <place>
                <number>2</number>
                <price>1000</price>
              </place>
              <place>
                <number>3</number>
                <price>1000</price>
              </place>
              <place>
                <number>4</number>
                <price>1000</price>
              </place>
              <place>
                <number>5</number>
                <price>1000</price>
              </place>
              <place>
                <number>6</number>
                <price>1000</price>
              </place>
              <place>
                <number>7</number>
                <price>1000</price>
              </place>
              <place>
                <number>8</number>
                <price>1000</price>
              </place>
              <place>
                <number>9</number>
                <price>1000</price>
              </place>
              <place>
                <number>10</number>
                <price>1000</price>
              </place>
              <place>
                <number>11</number>
                <price>1000</price>
              </place>
              <place>
                <number>12</number>
                <price>1000</price>
              </place>
              <place>
                <number>13</number>
                <price>1000</price>
              </place>
              <place>
                <number>14</number>
                <price>1000</price>
              </place>
              <place>
                <number>15</number>
                <price>1000</price>
              </place>
              <place>
                <number>16</number>
                <price>1000</price>
              </place>
            </row>
            <row >
              <row_number>8</row_number>
              <place>
                <number>1</number>
                <price>1000</price>
              </place>
              <place>
                <number>2</number>
                <price>1000</price>
              </place>
              <place>
                <number>3</number>
                <price>1000</price>
              </place>
              <place>
                <number>4</number>
                <price>1000</price>
              </place>
              <place>
                <number>5</number>
                <price>1000</price>
              </place>
              <place>
                <number>6</number>
                <price>1000</price>
              </place>
              <place>
                <number>7</number>
                <price>1000</price>
              </place>
              <place>
                <number>8</number>
                <price>1000</price>
              </place>
              <place>
                <number>9</number>
                <price>1000</price>
              </place>
              <place>
                <number>10</number>
                <price>1000</price>
              </place>
              <place>
                <number>11</number>
                <price>1000</price>
              </place>
              <place>
                <number>12</number>
                <price>1000</price>
              </place>
              <place>
                <number>13</number>
                <price>1000</price>
              </place>
              <place>
                <number>14</number>
                <price>1000</price>
              </place>
              <place>
                <number>15</number>
                <price>1000</price>
              </place>
              <place>
                <number>16</number>
                <price>1000</price>
              </place>
            </row>
            <row >
              <row_number>9</row_number>
              <place>
                <number>1</number>
                <price>1000</price>
              </place>
              <place>
                <number>2</number>
                <price>1000</price>
              </place>
              <place>
                <number>3</number>
                <price>1000</price>
              </place>
              <place>
                <number>4</number>
                <price>1000</price>
              </place>
              <place>
                <number>5</number>
                <price>1000</price>
              </place>
              <place>
                <number>6</number>
                <price>1000</price>
              </place>
              <place>
                <number>7</number>
                <price>1000</price>
              </place>
              <place>
                <number>8</number>
                <price>1000</price>
              </place>
              <place>
                <number>9</number>
                <price>1000</price>
              </place>
              <place>
                <number>10</number>
                <price>1000</price>
              </place>
              <place>
                <number>11</number>
                <price>1000</price>
              </place>
              <place>
                <number>12</number>
                <price>1000</price>
              </place>
              <place>
                <number>13</number>
                <price>1000</price>
              </place>
              <place>
                <number>14</number>
                <price>1000</price>
              </place>
              <place>
                <number>15</number>
                <price>1000</price>
              </place>
              <place>
                <number>16</number>
                <price>1000</price>
              </place>
            </row>
          </plane_zale>
        </x:parse>

        <table>
        <x:forEach  var="row" select="$zale/plane_zale/row">
          <tr>
            <x:forEach  var="place" select="$row/place">
              <td id="<x:out select="$row/row_number"/>_<x:out select="$place/number"/>"
                  style="border-style: groove; height: 25px; width: 25px; background-color: chartreuse;"
                  onclick="clickPlace(<x:out select="$row/row_number"/>,<x:out select="$place/number"/>)">
              </td>
            </x:forEach>
          </tr>
        </x:forEach>
        </table>

      <form name="send" action="booking" method="post">
        <input name="place" type=hidden>
        <input name="row" type=hidden>
        <input name="booking" type=hidden>
      </form>


          <c:forEach var="place" items="${zaleFree.isFree}">
              <script>
                document.getElementById(${place.row}+'_'+${place.place}).style.backgroundColor='red';
              </script>
          </c:forEach>


      <script>

        function clickPlace(row,place){

          if(document.getElementById(row+'_'+place).style.backgroundColor=='blue')
          {
            document.getElementById(row+'_'+place).style.backgroundColor='chartreuse';
            document.send.booking.value='true';
          }
          else
          {
            document.getElementById(row+'_'+place).style.backgroundColor='blue';
            document.send.booking.value='false';

          }
          document.send.place.value=place;
          document.send.row.value=row;
          document.send.submit();
        }
      </script>
  </body>
</html>
